// `raiden init`: generate a starter raiden.toml for the current machine, to make
// onboarding on real hardware a single command instead of hand-editing an
// example. it discovers candidate disks, detects the firmware mode, derives the
// partition prefix, and selects the stack-correct crypt block (mirroring the
// examples/ catalog), then writes a config the user reviews before `install`.
//
// interactive by default; --stack/--level/--members/--boot-mode pre-answer any
// step (and --non-interactive, or a non-tty stdin, takes the detected defaults),
// so the e2e suite drives it without real disks.

use std::collections::HashSet;
use std::io::IsTerminal;
use std::path::Path;

use anyhow::{bail, Context, Result};

use crate::cli::{Global, InitArgs};
use crate::config::{
    Config, Crypt, Family, Overrides, STACKS, STACK_MD_LVM_EXT4, STACK_MD_LVM_XFS,
};
use crate::prompt;

// efi when this firmware node is present; bios otherwise.
const EFI_FIRMWARE_PATH: &str = "/sys/firmware/efi";
// mountpoints whose backing disk is the running/live medium. those disks are
// excluded from the auto-selected members so the wizard never defaults to wiping
// the installer it booted from.
const LIVE_MOUNTPOINTS: &[&str] = &["/", "/run/live/medium", "/cdrom", "/lib/live/mount/medium"];

const HEADER: &str = "\
# raiden install-time config, generated by `raiden init`.
# review and edit before installing -- `raiden install` ERASES the member disks.
# see examples/ for annotated, per-stack configs. the encryption password is
# never stored here; raiden prompts for it.
";

struct Disk {
    name: String,
    size: u64,
    model: String,
    removable: bool,
    in_use: bool,
}

/// the `init` command: generate a config for this machine and write it for the
/// user to review before installing.
pub fn run(g: &Global, flags: &Overrides, args: &InitArgs) -> Result<()> {
    let output = args.output.clone().unwrap_or_else(|| g.config.clone());
    if output.exists() && !args.force {
        bail!("{} exists; pass --force to overwrite", output.display());
    }
    let interactive = !args.non_interactive && std::io::stdin().is_terminal();
    let cfg = generate(flags, args.boot_mode.as_deref(), interactive)?;
    if interactive && !confirm_summary(&cfg, &output)? {
        bail!("aborted");
    }
    write_config(&cfg, &output)?;
    println!("wrote {}", output.display());
    println!(
        "review it, then install with: raiden install --config {}",
        output.display()
    );
    Ok(())
}

/// assemble a machine-appropriate config from disk discovery and the (env+flag)
/// overrides, validated but not written. shared by `raiden init` and a config-less
/// `raiden install`, so a single command can provision from a bare live env.
pub fn generate(flags: &Overrides, boot_mode: Option<&str>, interactive: bool) -> Result<Config> {
    let o = Overrides::from_env().overlay(flags);
    let stack = resolve_stack(o.stack.as_deref(), interactive)?;
    let family = family_of(&stack)?;
    let members = resolve_members(o.disks.as_deref(), interactive)?;
    if members.is_empty() {
        bail!("no member disks chosen; pass --members or run where disks are visible");
    }
    let (prefix, mixed) = resolve_prefix(&members);
    if mixed {
        eprintln!(
            "warning: members mix partition-naming styles (eg. nvme vs sd); raiden uses one\n  \
             part_prefix for all members. prefer disks of one type, or fix disks.part_prefix."
        );
    }
    let level = resolve_level(o.level.as_deref(), family, members.len(), interactive)?;
    let boot = resolve_boot_mode(boot_mode, interactive)?;
    let cfg = assemble(
        &stack,
        &level,
        &members,
        prefix,
        &boot,
        o.release.as_deref(),
    );
    cfg.validate()
        .context("the chosen options do not form a valid config")?;
    Ok(cfg)
}

fn resolve_stack(flag: Option<&str>, interactive: bool) -> Result<String> {
    if let Some(s) = flag {
        return Ok(s.to_string());
    }
    if interactive {
        let i = prompt::choose("stack", STACKS, 0)?;
        return Ok(STACKS[i].to_string());
    }
    Ok(STACK_MD_LVM_EXT4.to_string())
}

fn family_of(stack: &str) -> Result<Family> {
    let mut c = Config::default();
    c.raid.stack = stack.to_string();
    c.family()
}

fn resolve_members(flag: Option<&[String]>, interactive: bool) -> Result<Vec<String>> {
    if let Some(m) = flag {
        return Ok(m.to_vec());
    }
    let disks = discover()?;
    if disks.is_empty() {
        bail!("no whole disks found; pass --members explicitly");
    }
    let safe: Vec<String> = disks
        .iter()
        .filter(|d| !d.removable && !d.in_use)
        .map(|d| d.name.clone())
        .collect();
    if !interactive {
        if safe.is_empty() {
            bail!("only removable/in-use disks found; pass --members to choose explicitly");
        }
        return Ok(safe);
    }
    select_disks(&disks, &safe)
}

/// present the discovered disks (size, model, and removable/in-use tags) and let
/// the operator pick members by number or name, defaulting to the safe set.
fn select_disks(disks: &[Disk], default: &[String]) -> Result<Vec<String>> {
    println!("candidate disks:");
    for (i, d) in disks.iter().enumerate() {
        let mut tags = Vec::new();
        if d.removable {
            tags.push("removable");
        }
        if d.in_use {
            tags.push("in use/live");
        }
        let tag = if tags.is_empty() {
            String::new()
        } else {
            format!(" [{}]", tags.join(", "))
        };
        println!(
            "  {}) {:12} {:>8}  {}{}",
            i + 1,
            d.name,
            human_size(d.size),
            d.model,
            tag
        );
    }
    let ans = prompt::ask(
        "member disks (numbers or names, comma-separated)",
        &default.join(","),
    )?;
    Ok(parse_selection(&ans, disks))
}

/// map a comma-separated answer (1-based numbers or bare names) to disk names,
/// keeping order and dropping duplicates.
fn parse_selection(ans: &str, disks: &[Disk]) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    for tok in ans.split(',').map(str::trim).filter(|t| !t.is_empty()) {
        let name = match tok.parse::<usize>() {
            Ok(n) if (1..=disks.len()).contains(&n) => disks[n - 1].name.clone(),
            _ => tok.to_string(),
        };
        if !out.contains(&name) {
            out.push(name);
        }
    }
    out
}

fn resolve_prefix(members: &[String]) -> (String, bool) {
    let first = part_prefix(&members[0]);
    let mixed = members.iter().any(|m| part_prefix(m) != first);
    (first.to_string(), mixed)
}

/// the kernel partition separator for a whole-disk name: "p" when the name ends
/// in a digit (nvme0n1 -> nvme0n1p1, mmcblk0 -> mmcblk0p1), empty otherwise
/// (sda -> sda1, vda -> vda1).
fn part_prefix(name: &str) -> &'static str {
    match name.chars().last() {
        Some(c) if c.is_ascii_digit() => "p",
        _ => "",
    }
}

fn resolve_level(
    flag: Option<&str>,
    family: Family,
    n: usize,
    interactive: bool,
) -> Result<String> {
    if let Some(l) = flag {
        return Ok(l.to_string());
    }
    let def = default_level(family, n);
    if interactive {
        return prompt::ask("raid level", &def);
    }
    Ok(def)
}

/// a sensible default raid level for the stack family and member count: the
/// highest redundancy the count supports, so the generated config validates.
fn default_level(family: Family, n: usize) -> String {
    match family {
        Family::Md => {
            if n >= 4 {
                "6"
            } else if n == 3 {
                "5"
            } else {
                "1"
            }
        }
        Family::Zfs => {
            if n >= 4 {
                "raidz2"
            } else {
                "raidz1"
            }
        }
        Family::Btrfs => {
            if n >= 3 {
                "raid1c3"
            } else {
                "raid1"
            }
        }
        // bcachefs redundancy is a replica count (1-4).
        Family::Bcachefs => {
            if n >= 2 {
                "2"
            } else {
                "1"
            }
        }
    }
    .to_string()
}

fn resolve_boot_mode(explicit: Option<&str>, interactive: bool) -> Result<String> {
    if let Some(b) = explicit {
        return Ok(b.to_string());
    }
    let def = if Path::new(EFI_FIRMWARE_PATH).exists() {
        "efi"
    } else {
        "bios"
    };
    if interactive {
        return prompt::ask("boot mode (efi/bios)", def);
    }
    Ok(def.to_string())
}

/// build the config from the resolved choices. defaults supply everything else;
/// crypt is overridden per stack so the integrity choice is correct out of the box.
fn assemble(
    stack: &str,
    level: &str,
    members: &[String],
    prefix: String,
    boot_mode: &str,
    release: Option<&str>,
) -> Config {
    let mut c = Config::default();
    c.raid.stack = stack.to_string();
    c.raid.level = level.to_string();
    c.disks.members = members.to_vec();
    c.disks.part_prefix = prefix;
    c.install.boot_mode = boot_mode.to_string();
    if let Some(r) = release {
        c.install.release = r.to_string();
    }
    c.crypt = crypt_for(stack);
    c
}

/// crypt settings per stack, matching examples/: aead (aegis128) for the md/lvm
/// ext4 and xfs stacks; a plain aes-xts cipher for the rest, where integrity is
/// provided by the filesystem (zfs/btrfs/bcachefs) or dm-integrity below md.
fn crypt_for(stack: &str) -> Crypt {
    let mut c = Crypt::default();
    if stack != STACK_MD_LVM_EXT4 && stack != STACK_MD_LVM_XFS {
        c.cipher = "aes-xts-plain64".to_string();
        c.key_size = 512;
        c.integrity = "none".to_string();
    }
    c
}

fn confirm_summary(cfg: &Config, output: &Path) -> Result<bool> {
    println!("\nplan:");
    println!("  stack:     {}", cfg.raid.stack);
    println!("  level:     {}", cfg.raid.level);
    println!("  members:   {}", cfg.disks.members.join(", "));
    println!("  boot mode: {}", cfg.install.boot_mode);
    println!(
        "  crypt:     {} ({})",
        cfg.crypt.cipher, cfg.crypt.integrity
    );
    println!("  output:    {}", output.display());
    prompt::confirm("write this config?")
}

fn write_config(cfg: &Config, output: &Path) -> Result<()> {
    let body = toml::to_string_pretty(cfg).context("serializing config")?;
    std::fs::write(output, format!("{HEADER}\n{body}"))
        .with_context(|| format!("writing {}", output.display()))
}

/// enumerate whole disks via lsblk (no partitions), tagging removable media and
/// the disk(s) backing the running/live medium.
fn discover() -> Result<Vec<Disk>> {
    let out = std::process::Command::new("lsblk")
        .args(["-dn", "-b", "-o", "NAME,SIZE,RM,TYPE,MODEL"])
        .output()
        .context("running lsblk to discover disks")?;
    if !out.status.success() {
        bail!(
            "lsblk failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    let in_use = in_use_disks();
    let text = String::from_utf8_lossy(&out.stdout);
    let mut disks = Vec::new();
    for line in text.lines() {
        // columns: NAME SIZE RM TYPE [MODEL...]; MODEL may have spaces or be empty.
        let mut it = line.split_whitespace();
        let (Some(name), Some(size), Some(rm), Some(ty)) =
            (it.next(), it.next(), it.next(), it.next())
        else {
            continue;
        };
        if ty != "disk" {
            continue;
        }
        let model = it.collect::<Vec<_>>().join(" ");
        disks.push(Disk {
            name: name.to_string(),
            size: size.parse().unwrap_or(0),
            model: if model.is_empty() {
                "(unknown)".to_string()
            } else {
                model
            },
            removable: rm == "1",
            in_use: in_use.contains(name),
        });
    }
    Ok(disks)
}

/// best-effort set of whole-disk names backing the live/root mountpoints, so the
/// installer medium is not offered as an install target. failures yield an empty
/// set (the operator still reviews the generated config).
fn in_use_disks() -> HashSet<String> {
    let mut set = HashSet::new();
    let Ok(mounts) = std::fs::read_to_string("/proc/mounts") else {
        return set;
    };
    for line in mounts.lines() {
        let mut f = line.split_whitespace();
        let (Some(src), Some(mnt)) = (f.next(), f.next()) else {
            continue;
        };
        if LIVE_MOUNTPOINTS.contains(&mnt) && src.starts_with("/dev/") {
            if let Some(disk) = parent_disk(src) {
                set.insert(disk);
            }
        }
    }
    set
}

/// the whole-disk kernel name backing a /dev node (lsblk PKNAME), or the node's
/// own basename when it is already a whole disk.
fn parent_disk(dev: &str) -> Option<String> {
    let out = std::process::Command::new("lsblk")
        .args(["-no", "PKNAME", dev])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let text = String::from_utf8_lossy(&out.stdout);
    let pk = text.lines().next().unwrap_or("").trim();
    if pk.is_empty() {
        dev.strip_prefix("/dev/").map(str::to_string)
    } else {
        Some(pk.to_string())
    }
}

fn human_size(bytes: u64) -> String {
    const UNITS: [&str; 6] = ["B", "K", "M", "G", "T", "P"];
    let mut v = bytes as f64;
    let mut u = 0;
    while v >= 1024.0 && u < UNITS.len() - 1 {
        v /= 1024.0;
        u += 1;
    }
    format!("{v:.0}{}", UNITS[u])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn part_prefix_follows_kernel_rule() {
        assert_eq!(part_prefix("sda"), "");
        assert_eq!(part_prefix("vda"), "");
        assert_eq!(part_prefix("nvme0n1"), "p");
        assert_eq!(part_prefix("mmcblk0"), "p");
    }

    #[test]
    fn resolve_prefix_flags_mixed_members() {
        let m = vec!["sda".to_string(), "sdb".to_string()];
        assert_eq!(resolve_prefix(&m), ("".to_string(), false));
        let m = vec!["nvme0n1".to_string(), "nvme1n1".to_string()];
        assert_eq!(resolve_prefix(&m), ("p".to_string(), false));
        let m = vec!["sda".to_string(), "nvme0n1".to_string()];
        assert!(resolve_prefix(&m).1);
    }

    #[test]
    fn default_level_fits_the_member_count() {
        assert_eq!(default_level(Family::Md, 4), "6");
        assert_eq!(default_level(Family::Md, 3), "5");
        assert_eq!(default_level(Family::Md, 2), "1");
        assert_eq!(default_level(Family::Zfs, 4), "raidz2");
        assert_eq!(default_level(Family::Zfs, 2), "raidz1");
        assert_eq!(default_level(Family::Btrfs, 3), "raid1c3");
    }

    #[test]
    fn crypt_matches_stack_integrity_choice() {
        assert_eq!(crypt_for(STACK_MD_LVM_EXT4).integrity, "aead");
        assert_eq!(crypt_for(STACK_MD_LVM_XFS).cipher, "aegis128-plain64");
        let zfs = crypt_for("dm-crypt~zfs");
        assert_eq!(zfs.cipher, "aes-xts-plain64");
        assert_eq!(zfs.integrity, "none");
        assert_eq!(zfs.key_size, 512);
    }

    #[test]
    fn assembled_config_validates() {
        let m = vec!["sda".to_string(), "sdb".to_string(), "sdc".to_string()];
        let c = assemble("dm-crypt~zfs", "raidz1", &m, "".to_string(), "efi", None);
        assert!(c.validate().is_ok());
        assert_eq!(c.crypt.integrity, "none");
    }
}
